import { JobPost, JobApplication, UserProfile, ApplicationStatus } from '../types';
import { db } from './firebaseConfig';
import { collection, addDoc, updateDoc, deleteDoc, doc, getDocs, query, where, setDoc, increment } from "firebase/firestore";

export const jobService = {
  // --- JOBS ---

  // Get all jobs (Now Async)
  getJobs: async (): Promise<JobPost[]> => {
    try {
      const q = query(collection(db, "jobs"));
      const querySnapshot = await getDocs(q);
      const jobs: JobPost[] = [];
      querySnapshot.forEach((doc) => {
        // Only return active or relevant jobs
        jobs.push({ id: doc.id, ...doc.data() } as JobPost);
      });
      // Sort by date descending
      return jobs.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    } catch (e) {
      console.error("Error loading jobs", e);
      return [];
    }
  },

  // Add a new job
  addJob: async (job: JobPost): Promise<void> => {
    // We use the ID generated by Firestore or passed in
    const jobRef = doc(collection(db, "jobs")); 
    const newJob = { ...job, id: jobRef.id }; // Ensure ID matches
    await setDoc(jobRef, newJob);
  },

  // Update an existing job
  updateJob: async (updatedJob: JobPost): Promise<void> => {
    const jobRef = doc(db, "jobs", updatedJob.id);
    await updateDoc(jobRef, { ...updatedJob });
  },

  // Delete a job
  deleteJob: async (id: string): Promise<void> => {
    await deleteDoc(doc(db, "jobs", id));
  },

  // --- APPLICATIONS ---

  // Get applications for a specific job
  getApplicationsByJobId: async (jobId: string): Promise<JobApplication[]> => {
    try {
      const q = query(collection(db, "applications"), where("jobId", "==", jobId));
      const querySnapshot = await getDocs(q);
      const apps: JobApplication[] = [];
      querySnapshot.forEach((doc) => {
        apps.push({ id: doc.id, ...doc.data() } as JobApplication);
      });
      return apps;
    } catch (e) {
      console.error(e);
      return [];
    }
  },

  // Get applications made by a specific worker
  getApplicationsByWorkerId: async (workerId: string): Promise<JobApplication[]> => {
    try {
      const q = query(collection(db, "applications"), where("workerId", "==", workerId));
      const querySnapshot = await getDocs(q);
      const apps: JobApplication[] = [];
      querySnapshot.forEach((doc) => {
        apps.push({ id: doc.id, ...doc.data() } as JobApplication);
      });
      return apps;
    } catch (e) {
      return [];
    }
  },

  // Apply for a job
  applyForJob: async (jobId: string, workerProfile: UserProfile): Promise<boolean> => {
    // Check if already applied
    const q = query(
      collection(db, "applications"), 
      where("jobId", "==", jobId),
      where("workerId", "==", workerProfile.uid)
    );
    const querySnapshot = await getDocs(q);
    
    if (!querySnapshot.empty) return false; // Already applied

    // Create Application
    const newApp: JobApplication = {
      id: "", // Will be set by Firestore
      jobId,
      workerId: workerProfile.uid,
      workerName: workerProfile.fullName,
      workerProfileSnapshot: workerProfile,
      status: ApplicationStatus.PENDING,
      appliedAt: new Date().toISOString()
    };
    
    const appRef = doc(collection(db, "applications"));
    newApp.id = appRef.id;
    await setDoc(appRef, newApp);

    return true;
  },

  // Update application status
  updateApplicationStatus: async (appId: string, newStatus: ApplicationStatus, currentJob: JobPost): Promise<boolean> => {
    const appRef = doc(db, "applications", appId);
    const jobRef = doc(db, "jobs", currentJob.id);

    try {
        await updateDoc(appRef, { status: newStatus });

        // If status changed to ACCEPTED, increment job worker count
        if (newStatus === ApplicationStatus.ACCEPTED) {
            // Using transaction or simple update. For simplicity:
            // Check current count first (passed via currentJob to avoid extra read, but ideally should be transactional)
            if (currentJob.currentWorkers < currentJob.requiredWorkers) {
                await updateDoc(jobRef, {
                    currentWorkers: increment(1)
                });
            }
        }
        
        // Handle rejection logic if needed (decrement), implemented simply here:
        if (newStatus === ApplicationStatus.REJECTED || newStatus === ApplicationStatus.PENDING) {
             // If we are reversing an acceptance, we should ideally check previous state.
             // For this simple demo, we assume status flow is strictly Pending -> Accepted/Rejected
        }

        return true;
    } catch (e) {
        console.error(e);
        return false;
    }
  }
};